apiVersion: v1
kind: ReplicationController
metadata:
  name: mariadb-rc
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: mariadb:10.1.14
        imagePullPolicy: Always
        name: mariadb
        ports:
        - containerPort: 3306
          hostPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: j48tu24^cnRJiX*HiaTg[}
        - mountPath: /etc/letsencrypt/
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mariadb-storage
      volumes:
      - name: mariadb-storage
        emptyDir: {}
