apiVersion: v1
kind: ReplicationController
metadata:
  name: $APP_NAME|default:wordpress| Enter your application name$
kuberdock:
  packageID: 0
  preDescription: |
    You are installing the application [b]WordPress[/b].
    The WordPress rich content management system can utilize plugins, widgets, and themes.
    All the components needed for this application correct work will also be installed: [b]MySQL[/b] server.
    Choose the amount of resources or use recommended parameters set by default.
    First choose package.
    When you click "Order now", you will get to order processing page.
  postDescription: |
    You have installed [b]WordPress![/b]
    Please find more information about WordPress software on the official website [url]https://wordpress.com[/url]
    To access [b]WordPress[/b] use this link: [url]http://%PUBLIC_ADDRESS%[/url]
  # required for cPanel to do proxy to user`s domain
  # proxy:
    # root:
      # container: wordpress
      # domain: $APP_DOMAIN|default:user_domain_list|Select application domain$
  appPackages:
    - name: S
      goodFor: beginner
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 1
          containers:
            - name: wordpress
              kubes: 2
    - name: M
      recommended: yes
      goodFor: regular use
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 1
          containers:
            - name: wordpress
              kubes: 4
    - name: L
      goodFor: business
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 2
          containers:
            - name: wordpress
              kubes: 2
spec:
  replicas: 1
  selector:
    app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress:4.5.2-apache
        #imagePullPolicy: Always
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: 95.164.68.193
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          value: j48tu24^cnRJiX*HiaTg[}
        - name: KD_APP_ID
          value: $PD_RAND|default:autogen|PD rand$
        ports:
          - containerPort: 80

#        volumeMounts:
#        - mountPath: /var/lib/mysql
#          name: mariadb-storage
#      volumes:
#      - name: mariadb-storage
#        emptyDir: {}
