apiVersion: v1
kind: ReplicationController
metadata:
  name: $APP_NAME|default:wordpress| Enter your application name$
  user: $USERNAME|default:user|Please enter user for domain "cl-owncloud.space"$
kuberdock:
  packageID: 0
  preDescription: |
    You are installing the application [b]WordPress[/b].
    The WordPress rich content management system can utilize plugins, widgets, and themes.
    Choose the amount of resources or use recommended parameters set by default.
    First choose package.
    When you click "Order now", you will get to order processing page.
  postDescription: |
    You have installed [b]WordPress![/b]
    Please find more information about WordPress software on the official website [url]https://wordpress.com[/url]
    To access [b]WordPress[/b] use this link: [url]http://$USERNAME$.cl-owncloud.space[/url] after installation
  appPackages:
    - name: S
      goodFor: beginner
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 1
          containers:
            - name: worker
              kubes: 1
            - name: wordpress
              kubes: 2
          persistentDisks:
            - name: wordpress-persistent-storage
              pdSize: 1
    - name: M
      recommended: yes
      goodFor: regular use
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 1
          containers:
            - name: worker
              kubes: 3
            - name: wordpress
              kubes: 4
          persistentDisks:
            - name: wordpress-persistent-storage
              pdSize: 1
    - name: L
      goodFor: business
      publicIP: true
      pods:
        -
          name: $APP_NAME$
          kubeType: 2
          containers:
            - name: worker
              kubes: 3
            - name: wordpress
              kubes: 8
          persistentDisks:
            - name: wordpress-persistent-storage
              pdSize: 2
spec:
  replicas: 1
  selector:
    app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
      - name: wordpress-persistent-storage
        persistentDisk:
          pdName: wordpress_www_$USERNAME$
      restartPolicy: Always
      containers:
      - image: wordpress:4.5.2-apache
        #imagePullPolicy: Always
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: 95.164.68.193
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          value: j48tu24^cnRJiX*HiaTg[}
        - name: WORDPRESS_DB_NAME
          value: $USERNAME$-wordpress
        ports:
          - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html
          name: wordpress-persistent-storage
        workingDir: /var/www/html
      - image: prefer/worker:0.13
        name: worker
        env:
        - name: KD_APP_ID
          value: $PD_RAND|default:autogen|PD rand$
        - name: KD_CERT_STAGING
          value: Staging
        command:
        - python3.5
        - main.py
        - $USERNAME$
        - $USERNAME$.cl-owncloud.space