apiVersion: v1
kind: ReplicationController
metadata:
  name: wordpress-rc
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      restartPolicy: OnFailure
      containers:
      - image: wordpress:4.5.2-apache
        imagePullPolicy: Always
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: 95.164.68.193
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          value: j48tu24^cnRJiX*HiaTg[}
        ports:
          - containerPort: 80
      - image: prefer/worker:0.3
        name: worker
        imagePullPolicy: Always
        command:
        - python3.5
        - main.py
        - user22
        - user22.cl-owncloud.space
        - wordpress-svc

#        volumeMounts:
#        - mountPath: /var/lib/mysql
#          name: mariadb-storage
#      volumes:
#      - name: mariadb-storage
#        emptyDir: {}
