apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  labels:
    app: wordpress
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: wordpress
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: wordpress-rc
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress:4.5.2-apache
        imagePullPolicy: Always
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: 95.164.68.193
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          value: j48tu24^cnRJiX*HiaTg[}
      - image: prefer:0.1
        imagePullPolicy: Always
        restartPolicy: Never
        command:
        - python3.5
        - user4
        - user4.cl-owncloud.xyz
        - wordpress-svc

#        volumeMounts:
#        - mountPath: /var/lib/mysql
#          name: mariadb-storage
#      volumes:
#      - name: mariadb-storage
#        emptyDir: {}
